### ISSUE TITLE
Reference on Wheatech.Activation . What is it for?

### ISSUE THREAD

**Issue by lobster2012-user** [edwardmeng/PowerMapper#1]
## If it is not required, remove it please.

Fast implementation. Very good.
Waiting for NET CORE implementation
Thanks!

**Comment by edwardmeng** [comment]
The Wheatech.Activation has been renamed to be MassActivation. And the reference will be removed in the next release.

**Comment by lobster2012-user** [comment]
When do you going transform the project on NET CORE?

**Comment by edwardmeng** [comment]
It is going to be transformed  from tomorrow. There will be lots of changes in plan:
1. Rename to PowerMapper
2. Decouple with the Wheatech.Activation
3. Compatible with NetCore
4. More unit tests.

**Comment by lobster2012-user** [comment]
Very good.
